"""
GitHub PR automation
===================

Turns generated patches into a pull request:

  * writes each patch as a unified diff,
  * (optionally) creates a branch, commits the patches, and opens a PR via the
    GitHub REST API using a token from the environment (GITHUB_TOKEN).

Two modes:
  * ``export_patches`` -- always available, no network: writes .patch files and
    a combined PR body (Markdown) that a human can apply / open manually.
  * ``open_pull_request`` -- uses the GitHub API to push a branch and open a PR
    automatically. Requires GITHUB_TOKEN and a git working tree.

This keeps CI usage safe-by-default (export) while supporting full automation
when credentials are present.
"""

import json
import os
import subprocess
from datetime import datetime

import requests

API = "https://api.github.com"


def export_patches(patches, out_dir):
    """Write patches as .patch files plus a Markdown PR body. Returns paths."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for i, p in enumerate(patches):
        if not p.get("diff"):
            continue
        path = os.path.join(out_dir, f"fix_{i+1}_{p.get('finding_type','issue').replace(' ', '_')[:30]}.patch")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(p["diff"])
        written.append(path)

    body = build_pr_body(patches)
    body_path = os.path.join(out_dir, "PR_BODY.md")
    with open(body_path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return {"patches": written, "pr_body": body_path}


def build_pr_body(patches):
    lines = ["## LogicBreaker AI — automated security fixes", "",
             "This PR was generated by LogicBreaker AI. Each fix addresses a detected "
             "vulnerability. Verified fixes were confirmed by re-running a live exploit "
             "against a patched sandbox copy.", ""]
    verified = [p for p in patches if p.get("status") == "VERIFIED_FIX"]
    others = [p for p in patches if p.get("status") != "VERIFIED_FIX" and p.get("diff")]

    if verified:
        lines.append("### ✓ Verified fixes (re-tested)")
        for p in verified:
            v = p.get("verification", {})
            lines.append(f"- **{p.get('finding_type')}** in `{p.get('file')}` — "
                         f"re-attack: {v.get('successful_actions')} success, "
                         f"value now {v.get('final_value')}, vulnerable={v.get('vulnerable')}")
        lines.append("")
    if others:
        lines.append("### Suggested fixes (review before merge)")
        for p in others:
            note = p.get("note", "")
            lines.append(f"- **{p.get('finding_type')}** in `{p.get('file')}`"
                         + (f" — {note}" if note else ""))
        lines.append("")
    lines.append("---")
    lines.append(f"_Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} · review all changes before merging._")
    return "\n".join(lines)


def _run(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def open_pull_request(patches, repo_dir, repo_slug=None, base="main",
                      branch=None, token=None, title=None):
    """
    Create a branch, apply patches, commit, push, and open a PR.

    repo_slug: "owner/name" (auto-detected from origin remote if omitted)
    """
    token = token or os.environ.get("GITHUB_TOKEN")
    if not token:
        return {"ok": False, "reason": "GITHUB_TOKEN not set"}
    if not os.path.isdir(os.path.join(repo_dir, ".git")):
        return {"ok": False, "reason": f"{repo_dir} is not a git repository"}

    branch = branch or f"logicbreaker/fixes-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    title = title or "LogicBreaker AI: automated security fixes"

    if not repo_slug:
        remote = _run(["git", "remote", "get-url", "origin"], repo_dir)
        url = remote.stdout.strip()
        repo_slug = _slug_from_url(url)
        if not repo_slug:
            return {"ok": False, "reason": "could not determine repo slug; pass repo_slug"}

    # branch + apply
    cb = _run(["git", "checkout", "-b", branch], repo_dir)
    if cb.returncode != 0:
        return {"ok": False, "reason": f"git checkout failed: {cb.stderr}"}

    applied = 0
    for p in patches:
        if not p.get("diff"):
            continue
        proc = subprocess.run(["git", "apply", "--whitespace=nowarn", "-"],
                              cwd=repo_dir, input=p["diff"], capture_output=True, text=True)
        if proc.returncode == 0:
            applied += 1
    if applied == 0:
        return {"ok": False, "reason": "no patches applied cleanly"}

    _run(["git", "add", "-A"], repo_dir)
    _run(["git", "commit", "-m", title], repo_dir)

    push_url = f"https://x-access-token:{token}@github.com/{repo_slug}.git"
    push = _run(["git", "push", push_url, f"HEAD:{branch}"], repo_dir)
    if push.returncode != 0:
        return {"ok": False, "reason": f"git push failed: {push.stderr[:200]}"}

    # open PR
    resp = requests.post(
        f"{API}/repos/{repo_slug}/pulls",
        headers={"Authorization": f"Bearer {token}",
                 "Accept": "application/vnd.github+json"},
        json={"title": title, "head": branch, "base": base,
              "body": build_pr_body(patches)},
        timeout=30,
    )
    if resp.status_code >= 300:
        return {"ok": False, "reason": f"PR API error {resp.status_code}: {resp.text[:200]}",
                "branch_pushed": branch}
    pr = resp.json()
    return {"ok": True, "pr_url": pr.get("html_url"), "branch": branch, "patches_applied": applied}


def _slug_from_url(url):
    url = url.strip()
    if url.startswith("git@github.com:"):
        return url.split(":", 1)[1].removesuffix(".git")
    if "github.com/" in url:
        return url.split("github.com/", 1)[1].removesuffix(".git")
    return None
